package registry

// GetTraeCNModels returns the available models for Trae CN (ByteDance).
// These models are served through the Trae SOLO agent API.
func GetTraeCNModels() []*ModelInfo {
	now := int64(1753891200) // 2025-07-31
	return []*ModelInfo{
		{
			ID:                  "auto",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "Auto",
			Description:         "Automatic model selection via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "work",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "Work (Fast Auto)",
			Description:         "Fast auto mode via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gemini-3.1-pro",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "Gemini 3.1 Pro",
			Description:         "Gemini 3.1 Pro via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gemini-3-flash-solo",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "Gemini 3 Flash",
			Description:         "Gemini 3 Flash via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "minimax-m3",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "MiniMax M3",
			Description:         "MiniMax M3 via Trae CN",
			ContextLength:       1048576,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "minimax-m2.7",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "MiniMax M2.7",
			Description:         "MiniMax M2.7 via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k2.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "Kimi K2.5",
			Description:         "Kimi K2.5 via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-5.4",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "GPT 5.4",
			Description:         "GPT 5.4 via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-5.2",
			Object:              "model",
			Created:             now,
			OwnedBy:             "trae-cn",
			Type:                "trae-cn",
			DisplayName:         "GPT 5.2",
			Description:         "GPT 5.2 via Trae CN",
			ContextLength:       272000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
	}
}
